### ISSUE TITLE
Add a hub

### ISSUE THREAD

**Issue by andybluenoes** [Zingabopp/BeatSaberMultiplayerServerRepo#3]
Hi
Please can you add my hub server into the mod?
bluenoes.ddns.net
Many thanks
Andy

**Comment by Zingabopp** [comment]
Added

**Comment by Zingabopp** [comment]
New mod version requires a ServerHub update https://github.com/Zingabopp/BeatSaberMultiplayer/releases/tag/7.1.0-L
